import {
  Activity,
  AlertTriangle,
  Archive,
  BarChart3,
  Building2,
  Cpu,
  Database,
  FileText,
  Gauge,
  HardDrive,
  Layers,
  LayoutDashboard,
  Network,
  Plug,
  Radio,
  Receipt,
  ScrollText,
  Server,
  Settings,
  Shield,
  ShieldCheck,
  Users,
  Workflow,
} from 'lucide-react'
import type { ControlNavSection } from '../../types/dashboard'

export const controlNavSections: ControlNavSection[] = [
  {
    id: 'main',
    label: 'Main',
    items: [
      { label: 'Overview', path: '/', icon: LayoutDashboard },
      { label: 'Services', path: '/apm', icon: Cpu },
      { label: 'Infrastructure', path: '/cc/infrastructure', icon: Server },
      { label: 'Logs', path: '/logs', icon: FileText },
      { label: 'Alerts', path: '/alerts', icon: AlertTriangle, badge: { label: '5', tone: 'error' } },
      { label: 'Metrics', path: '/metrics', icon: Activity },
      { label: 'Tracing', path: '/cc/tracing', icon: Workflow },
      { label: 'Databases', path: '/cc/databases', icon: Database },
      { label: 'Queues', path: '/cc/queues', icon: Layers },
      { label: 'Users', path: '/users', icon: Users },
      { label: 'Tenants', path: '/clinics', icon: Building2 },
      { label: 'Settings', path: '/settings', icon: Settings },
    ],
  },
  {
    id: 'monitoring',
    label: 'Monitoring',
    items: [
      { label: 'System Health', path: '/cc/system-health', icon: Gauge },
      { label: 'Performance', path: '/cc/performance', icon: BarChart3 },
      { label: 'Network', path: '/cc/network', icon: Network },
      { label: 'Security', path: '/cc/security', icon: Shield },
      { label: 'Backups', path: '/cc/backups', icon: Archive },
      { label: 'Integrations', path: '/integrations', icon: Plug },
    ],
  },
  {
    id: 'administration',
    label: 'Administration',
    items: [
      { label: 'Roles', path: '/administrators', icon: ShieldCheck },
      { label: 'Audit Logs', path: '/cc/audit', icon: ScrollText },
      { label: 'Billing', path: '/cc/billing', icon: Receipt },
      { label: 'Configuration', path: '/cc/configuration', icon: HardDrive },
      { label: 'Monitors', path: '/monitors', icon: Radio },
    ],
  },
]
