global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    environment: 'medicare'

rule_files:
  - /etc/prometheus/alerts.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'api-gateway'
    static_configs:
      - targets: ['api-gateway:3000']
    metrics_path: '/metrics'

  - job_name: 'auth-service'
    static_configs:
      - targets: ['auth-service:3001']
    metrics_path: '/metrics'

  - job_name: 'user-service'
    static_configs:
      - targets: ['user-service:3002']
    metrics_path: '/metrics'

  - job_name: 'system-manager-service'
    static_configs:
      - targets: ['system-manager-service:3003']
    metrics_path: '/metrics'

  - job_name: 'clinic-service'
    static_configs:
      - targets: ['clinic-service:3006']
    metrics_path: '/metrics'

  - job_name: 'appointment-service'
    static_configs:
      - targets: ['appointment-service:3007']
    metrics_path: '/metrics'

  - job_name: 'scheduling-service'
    static_configs:
      - targets: ['scheduling-service:3008']
    metrics_path: '/metrics'

  - job_name: 'notification-service'
    static_configs:
      - targets: ['notification-service:3009']
    metrics_path: '/metrics'

  - job_name: 'reminder-service'
    static_configs:
      - targets: ['reminder-service:3010']
    metrics_path: '/metrics'
